config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  get 'users/new'

  get 'welcome/index'

  resources :articles do
    resources :comments
  end

  root 'welcome#index'

  get '/micropost', to: 'static_pages#home'

  get '/contact', to: 'welcome#contact'

  get '/about', to: 'welcome#about'

  get '/help', to: 'welcome#help'

  get  '/signup',  to: 'users#new'

  post '/signup',  to: 'users#create'

  get    '/login',   to: 'sessions#new'

  post   '/login',   to: 'sessions#create'

  delete '/logout',  to: 'sessions#destroy'

  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  resources :users do
    member do
      get :following, :followers
    end
  end

end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :comments, dependent: :destroy

  validates :title, presence: true, length: {maximum: 10}
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  #http_basic_authenticate_with name: "name", password: "password", except:[:index,:show]


  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end

  def show
    @article = Article.find(params[:id])
  end
  private
    def article_params
      params.require(:article).permit(:title,:text)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>

  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>

  <p>
    <%= f.submit "发帖"%>
  </p>

<% end %>

app/views/articles/edit.html.erb
<% provide(:title, "编辑博文") %>
<h1>编辑帖子</h1>
<hr>
<%= render 'form' %>

<%= link_to '回到匿名灌水区',articles_path, class: "btn btn-lg btn-success" %>

app/views/articles/index.html.erb
<% provide(:title, "主页") %>
  <div class="center jumbotron">
  <h1 style="text-align:center">匿名灌水区</h1>
  <hr>
  <!--<%= link_to "注册账号", signup_path, class: "btn btn-lg btn-success" %>
  <hr>-->
  <div>
  <%= image_tag("cat.jpg", alt: "cat") %>
  <br>
  <strong>没有猫的网站是没有灵魂的</strong>
  </div>
  <hr>
  <%= link_to '匿名发帖', new_article_path,class: "btn btn-lg btn-primary" %>
  <hr>

  <table>
    <tr><caption>测试用的凑数文章</caption>
      <th>标题</th>

    </tr>
    <% @articles.each do |article| %>
      <tr>
        <!--<td><%= article.title %></td>-->
        <td><%= link_to article.title, article_path(article) %></td>
        <!--<td><%= link_to '编辑', edit_article_path(article) %></td>
        <td><%= link_to '删除', article_path(article), method: :delete, data: {confirm: '确定删除?'} %></td>-->
      </tr>
    <% end %>
  </table>

</div>

app/views/articles/new.html.erb
<% provide(:title, "创建新博文") %>
<h1>这里用来写帖子</h1>
<hr>
<%= render 'form' %>

<%= link_to '回到匿名灌水区',articles_path, class: "btn btn-lg btn-success" %>

app/views/articles/show.html.erb
<% provide(:title, @article.title) %>
<p>
  <strong>标题:</strong>
  <%= @article.title %>
</p>
<p>
  <strong>正文:</strong>
  <%= @article.text %>
</p>

<h2>评论区</h2>
<%= render @article.comments %>

<h2>添加评论:</h2>
<%= render 'comments/form' %>


<% if !current_user.nil? && current_user.admin? %>
  <%= link_to '只有管理员才能编辑帖子', edit_article_path(@article), class: "btn btn-lg btn-primary"%>
  <br><br>
  <%= link_to '只有管理员才能删帖', article_path(@article), method: :delete, class: "btn btn-lg btn-danger", data: {confirm: '确定删除?'} %>
  <br>
<% end %>
<br>
<%= link_to '回到匿名灌水区',articles_path, class: "btn btn-lg btn-success"%>