config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  get 'users/new'

  get 'welcome/index'

  resources :articles do
    resources :comments
  end

  root 'welcome#index'

  get '/micropost', to: 'static_pages#home'

  get '/contact', to: 'welcome#contact'

  get '/about', to: 'welcome#about'

  get '/help', to: 'welcome#help'

  get  '/signup',  to: 'users#new'

  post '/signup',  to: 'users#create'

  get    '/login',   to: 'sessions#new'

  post   '/login',   to: 'sessions#create'

  delete '/logout',  to: 'sessions#destroy'

  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  resources :users do
    member do
      get :following, :followers
    end
  end

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_form.html.erb
<%= form_for (@user) do |f| %>
  <%= render 'shared/error_messages', object: @user %>
  <%= f.label :name, "姓名/name" %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :email, "邮件地址/email" %>
  <%= f.email_field :email, class: 'form-control' %>

  <%= f.label :password, "密码/password" %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label :password_confirmation, "确认密码/Confirmation" %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>


  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "写新微博..." %>
  </div>
  <%= f.submit "发布", class: "btn btn-primary" %>
  <!--<span class="picture">
    <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
  </span>-->
<% end %>

<script type="text/javascript">
  $('#micropost_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('文件最大5MB，请选择更小的文件');
    }
  });
</script>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "个人资料", current_user %></span>
<span><%= "微博数" %><%= current_user.microposts.count %></span>