config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  get 'users/new'

  get 'welcome/index'

  resources :articles do
    resources :comments
  end

  root 'welcome#index'

  get '/micropost', to: 'static_pages#home'

  get '/contact', to: 'welcome#contact'

  get '/about', to: 'welcome#about'

  get '/help', to: 'welcome#help'

  get  '/signup',  to: 'users#new'

  post '/signup',  to: 'users#create'

  get    '/login',   to: 'sessions#new'

  post   '/login',   to: 'sessions#create'

  delete '/logout',  to: 'sessions#destroy'

  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  resources :users do
    member do
      get :following, :followers
    end
  end

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    链接到<a href="https://www.twitter.com">推特</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "关于本应用/About",   about_path %></li>
      <li><%= link_to "联系我们/Contact", contact_path %></li>
      <li>链接到<a href="https://www.zhihu.com/">知乎</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top bg-primary navbar-inverse">
      <div class="container">
        <%= link_to "注册用户微博", micropost_path, id: "logo" %>
        <%= link_to "匿名灌水区", articles_path, id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "注册账号", signup_path, class: "btn btn-lg btn-primary" %></li>
            <li><%= link_to "主页/Home",   root_path %></li>
            <li><%= link_to "帮助/Help",   help_path %></li>
            <% if logged_in? %>
              <li><%= link_to "用户列表", users_path %></li>

              <li class="dropdown">

                <a href="#" class="dropdown-toggle" data-toggle="dropdown" >
                  账号/Account <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "个人资料/Profile", current_user %></li>
                  <li><%= link_to "修改资料/Settings", edit_user_path(current_user) %></li>
                  <li class="divider"></li>
                  <li>
                    <%= link_to "退出/Log out", logout_path, method: "delete" %>
                  </li>
                </ul>
              </li>
            <% else %>
              <li><%= link_to "登录/Log in", login_path %></li>
            <% end %>
          </ul>
        </nav>
      </div>
  </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

</head>
<body>

  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |message_type, message| %>
      <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
     <!--<%= debug(params) if Rails.env.development? %>-->
  </div>
</body>
</html>